apiVersion: v1
kind: ConfigMap
metadata:
  name: bird-config
  namespace: bird
data:
  DB_HOST: "db-service"
  UMS_URL: "http://ums-service:8081"
  TWITTER_URL: "http://twitter-service:8082"
  CORS_ORIGINS: "http://localhost:5173,http://localhost:3000,http://127.0.0.1"
