apiVersion: v1
kind: Secret
metadata:
  name: bird-secrets
  namespace: bird
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "birdpassword123"
  JWT_SECRET: "birdApplicationSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong"
  GITHUB_CLIENT_ID: "Ov23liWrkSx6BYO2argW"
  GITHUB_CLIENT_SECRET: "ffde2eb42662edc4baed9b391de1ba21744a9279"
  MYSQL_ROOT_PASSWORD: "birdpassword123"
